# Site Metadata
title: Jacob Christopher
logo: /assets/img/headshot_circle.png
#description: >
#  [Google Scholar](https://scholar.google.com/citations?user=z_PoUQAAAAJ&hl=en) | 
#  [LinkedIn](https://www.linkedin.com/in/jacob-christopher-834a02239/) | 
#  [Email](mailto:csk4sr@virginia.edu)
description: >
  Ph.D. Student in Computer Science at the University of Virginia
  Focus Areas: Generative AI, Responsible AI, Differentiable Optimization
show_download: false
favicon: /assets/img/favicon-32x32.png

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme

# Site settings
baseurl: ""
url: "https://jacobchristopher.github.io"

# Social Links
social_links:
  - name: Google Scholar
    url: https://scholar.google.com/citations?user=z_PoUQAAAAJ&hl=en
    icon: fa-graduation-cap
  - name: LinkedIn
    url: https://www.linkedin.com/in/jacob-christopher-834a02239/
    icon: fa-linkedin
  - name: Email
    url: mailto:csk4sr@virginia.edu
    icon: fa-envelope

# Navigation
navigation:
  - title: Home
    url: /
  - title: Publications
    url: /publications
  - title: CV
    url: /cv
