title: Jacob K. Christopher
logo: /assets/img/headshot_circle.png
description: PhD Student @ University of Virginia
show_download: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
