title: Jacob Christopher
logo: /assets/img/headshot_circle.png
description: PhD Student @ University of Virginia
show_download: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

minimal:
  social_links: true

# Add a link for Google Scholar
social_links:
  - name: Google Scholar
    url: https://scholar.google.com/citations?user=z_PoUQAAAAJ&hl=en
    icon: fa-solid fa-graduation-cap

    - name: LinkedIn
    url: https://www.linkedin.com/in/jacob-christopher-834a02239/
    icon: fa-linkedin

